### PR TITLE
validateISOID: allow SCOS images

### PR DESCRIPTION
**Pull request by vrutkovs**
## Description

Allow images with "scos-" volume ID. This is required to setup OKD SCOS via Assisted Installer

## How was this code tested?

Manual run

## Assignees

/cc @carbonin 
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR
- [ ] Relevant issues have been associated
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit tests (note that code changes require unit tests)

### CODE REVIEW

**Comment by vrutkovs** [comment]
Added unit tests, but since we don't have SCOS images pushed to official S3 bucket I can add integration test later. Lets

/hold

it for now

**Comment by vrutkovs** [comment]
/hold cancel

SCOS builds are not public, added integration test

**Comment by carbonin** [comment]
> SCOS builds are not public, added integration test

What does this mean for us? I mean, you added a test so they are downloadable, but they're not public in that they don't get published the same way?

**Comment by vrutkovs** [comment]
>What does this mean for us? I mean, you added a test so they are downloadable, but they're not public in that they don't get published the same way?

Oh, sorry, there _were_ not public when I wrote that comment and I assumed it would take a while to get them published. Luckily it was easy and SCOS builds are downloadable freely

**Review by carbonin — APPROVED** [review]

**Pull request merged**
