### PR TITLE
MGMT-18385 - updating golang to 1.21

### PR DESCRIPTION
**Pull request by eifrach**
## Description

- update golang to 1.21
- 

## Assignees

/cc @
/cc @

## Checklist

- [ ] Title and description added to both, commit and PR
- [ ] Relevant issues have been associated
- [ ] Reviewers have been listed
- [ ] This change does not require a documentation update (docstring, `docs`, README, etc)
- [ ] Does this change include unit tests (note that code changes require unit tests)

### CODE REVIEW

**Comment by rccrdpccl** [comment]
I think it most likely has been missed, everything else is set to 1.21 (go.mod), so it should be 1.21 in Dockerfile too

/lgtm

**Comment by pastequo** [comment]
I was keeping the go version consistent, maybe not for this one. At some point build & licenses step could be merged into one

**Pull request merged**
