### PR TITLE
WIP NO-ISSUE: Bump golangci-lint to 1.45.2

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by carbonin** [comment]
Maybe use what assisted-service is using?
https://github.com/openshift/assisted-service/blob/master/hack/setup_env.sh#L73-L74

Or is there an issue with that version too we think?

**Comment by vrutkovs** [comment]
I was thinking we could update both, starting with this repo.

However, the issue is that we did `go import` which broke down - and apparently not needed for tests?

**Comment by carbonin** [comment]
> However, the issue is that we did go import which broke down - and apparently not needed for tests?

Do you mean removing `go get -u golang.org/x/tools/cmd/goimports@v0.1.5 github.com/golang/mock/mockgen@v1.6.0` is what fixed it?

I think we need that for `make format` unless we're not running that in the CI?

**Comment by carbonin** [comment]
If this fixes the issue and we don't need to use these commands in CI then I'm okay with removing them I guess :shrug:

**Comment by vrutkovs** [comment]
> Do you mean removing go get -u golang.org/x/tools/cmd/goimports@v0.1.5 github.com/golang/mock/mockgen@v1.6.0 is what fixed it?

Right, I'll check if `make format` works without these and split this change in a different PR

**Comment by vrutkovs** [comment]
Will be reworked after #76

**Comment by vrutkovs** [comment]
This bump is useless since `golangci-lint` version is defined in the image :/

**Pull request closed without merging**
